### ISSUE TITLE
Не отображается после установки

### ISSUE THREAD

**Issue by DrChook** [Buksa/movian-plugin-anidub#1]
Проверял на showtime_4.9.46_i386.deb и PS3

После обновления до версии 1.1.1 не отображается на главном экране.
Проблема в том что в файле plugin.json пропала строка "apiversion": 1,
Теперь пользоваться плагином стало нельзя.

Кроме того, после выбора названия аниме, почти все тайтлы дают пустой список серий.
Опять таки пользоваться плагином стало невозможно :( В чем тут проблема - я не знаю. Версия 1.0.2 так же не выдает список серий для просмотра.

**Comment by Buksa** [comment]
movian должен быть Bleeding Edge на данный момент не ниже 4.9.452
https://movian.tv/downloads/movian/master
